update

diff --git a/ssh_check_bin_dir b/ssh_check_bin_dir
--- a/ssh_check_bin_dir
+++ b/ssh_check_bin_dir
@@ -1,30 +1,32 @@
 #!/bin/bash
 
-l="export PATH=\$PATH:~/bin"
+bp="~/bin"
+bp=$(ssh $1 "echo \$(readlink -f $bp)")
+l="export PATH=\$PATH:$bp"
 p=". ~/.profile;"
-ssh $1 "$p echo \$PATH | grep '~/bin'"
+ssh $1 "$p echo \$PATH | grep '$bp'"
 
 if [ $? -ne 0 ]; then
-	echo "[!] ~/bin not found in PATH, checking ~/.bashrc"
+	echo "[!] $bp not found in PATH, checking ~/.bashrc"
 	ssh $1 "$p echo \$PATH; cat ~/.bashrc | grep '$l'"
 	if [ $? -ne 0 ]; then
 		echo "[!] adding bin path to ~/.bashrc ~/.profile"
-		ssh $1 "echo 'export PATH=\$PATH:~/bin' >> ~/.bashrc"
-		ssh $1 "echo 'export PATH=\$PATH:~/bin' >> ~/.profile"
-		ssh $1 "echo 'export PATH=\$PATH:~/bin' >> ~/.bash_profile"
+		ssh $1 "echo 'export PATH=\$PATH:$bp' >> ~/.bashrc"
+		ssh $1 "echo 'export PATH=\$PATH:$bp' >> ~/.profile"
+		ssh $1 "echo 'export PATH=\$PATH:$bp' >> ~/.bash_profile"
 	fi
 else
 	echo "[+] ~/bin found in PATH"
 fi
 
-ssh $1 "$p echo \$PATH | grep '~/bin'"
+ssh $1 "$p echo \$PATH | grep '$bp'"
 
 if [ $? -ne 0 ]; then
-	echo "[E] ~/bin not found in PATH"
+	echo "[E] $bp not found in PATH"
 	exit 1
 fi
 
-ssh $1 "if [ -d ~/bin ]; then exit 0; else exit 1; fi"
+ssh $1 "if [ -d $bp ]; then exit 0; else exit 1; fi"
 
 if [ $? -ne 0 ]; then
         scp -r ~/bin $1:~/
